//package org.example;
//
//public class orderitemsd {
////    ORDER_ID VARCHAR(40) NOT NULL,
////    ->     ORDER_ITEM_SEQ_ID VARCHAR(40) NOT NULL,
////    ->     ORDER_PART_SEQ_ID VARCHAR(40) DEFAULT NULL,
////    ->     PRODUCT_ID VARCHAR(40) DEFAULT NULL,
////    ->     ITEM_DESCRIPTION VARCHAR(255) DEFAULT NULL,
////    ->     QUANTITY DECIMAL(26,6) DEFAULT NULL,
////    ->     UNIT_AMOUNT DECIMAL(25,5) DEFAULT NULL,
////    ->     ITEM_TYPE_ENUM_ID VARCHAR(40) DEFAULT NULL,
////    ->     PARENT_ITEM_SEQ_ID VARCHAR(40) DEFAULT NULL,
//
//
//}
